# coding: utf-8

"""
    flows_filtered Mitmproxy2Swagger

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import woolworths
from woolworths.models.inline_response20029 import InlineResponse20029  # noqa: E501
from woolworths.rest import ApiException


class TestInlineResponse20029(unittest.TestCase):
    """InlineResponse20029 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20029(self):
        """Test InlineResponse20029"""
        # FIXME: construct object with mandatory attributes with example values
        # model = woolworths.models.inline_response20029.InlineResponse20029()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
