# coding: utf-8

"""
    flows_filtered Mitmproxy2Swagger

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import woolworths
from woolworths.api.default_api import DefaultApi  # noqa: E501
from woolworths.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_ui_v2_bootstrap_get(self):
        """Test case for api_ui_v2_bootstrap_get

        GET bootstrap  # noqa: E501
        """
        pass

    def test_api_v3_ui_authentication_otp_post(self):
        """Test case for api_v3_ui_authentication_otp_post

        POST otp  # noqa: E501
        """
        pass

    def test_api_v3_ui_checkout_digitalpay_instruments_get(self):
        """Test case for api_v3_ui_checkout_digitalpay_instruments_get

        GET instruments  # noqa: E501
        """
        pass

    def test_api_v3_ui_fulfilment_feestructure_id_get(self):
        """Test case for api_v3_ui_fulfilment_feestructure_id_get

        GET feestructure by id  # noqa: E501
        """
        pass

    def test_api_v3_ui_fulfilment_windows_get(self):
        """Test case for api_v3_ui_fulfilment_windows_get

        GET windows  # noqa: E501
        """
        pass

    def test_api_v3_ui_mylists_get(self):
        """Test case for api_v3_ui_mylists_get

        GET mylists  # noqa: E501
        """
        pass

    def test_api_v3_ui_order_amending_get(self):
        """Test case for api_v3_ui_order_amending_get

        GET amending  # noqa: E501
        """
        pass

    def test_api_v3_ui_packaging_preferences_get(self):
        """Test case for api_v3_ui_packaging_preferences_get

        GET packagingpreferences  # noqa: E501
        """
        pass

    def test_api_v3_ui_packaging_preferences_id_post(self):
        """Test case for api_v3_ui_packaging_preferences_id_post

        POST packagingpreferences by id  # noqa: E501
        """
        pass

    def test_api_v3_ui_trolley_update_post(self):
        """Test case for api_v3_ui_trolley_update_post

        POST trolley update  # noqa: E501
        """
        pass

    def test_apis_ui_checkout_confirm_order_get(self):
        """Test case for apis_ui_checkout_confirm_order_get

        GET confirmorder  # noqa: E501
        """
        pass

    def test_apis_ui_checkout_digital_pay_initialize_credit_card_iframe_post(self):
        """Test case for apis_ui_checkout_digital_pay_initialize_credit_card_iframe_post

        POST initializecreditcardiframe  # noqa: E501
        """
        pass

    def test_apis_ui_checkout_digital_pay_payment_post(self):
        """Test case for apis_ui_checkout_digital_pay_payment_post

        POST payment  # noqa: E501
        """
        pass

    def test_apis_ui_checkout_get(self):
        """Test case for apis_ui_checkout_get

        GET checkout  # noqa: E501
        """
        pass

    def test_apis_ui_delivery_delivery_info_get(self):
        """Test case for apis_ui_delivery_delivery_info_get

        GET deliveryinfo  # noqa: E501
        """
        pass

    def test_apis_ui_delivery_options_get(self):
        """Test case for apis_ui_delivery_options_get

        GET options  # noqa: E501
        """
        pass

    def test_apis_ui_delivery_options_post(self):
        """Test case for apis_ui_delivery_options_post

        POST options  # noqa: E501
        """
        pass

    def test_apis_ui_fulfilment_post(self):
        """Test case for apis_ui_fulfilment_post

        POST fulfilment  # noqa: E501
        """
        pass

    def test_apis_ui_inspiration_cards_get(self):
        """Test case for apis_ui_inspiration_cards_get

        GET cards  # noqa: E501
        """
        pass

    def test_apis_ui_login_loginwithcredential_post(self):
        """Test case for apis_ui_login_loginwithcredential_post

        POST loginwithcredential  # noqa: E501
        """
        pass

    def test_apis_ui_pastshops_list_get(self):
        """Test case for apis_ui_pastshops_list_get

        GET list  # noqa: E501
        """
        pass

    def test_apis_ui_pies_categories_with_specials_get(self):
        """Test case for apis_ui_pies_categories_with_specials_get

        GET piescategorieswithspecials  # noqa: E501
        """
        pass

    def test_apis_ui_product_haveyouforgotten_get(self):
        """Test case for apis_ui_product_haveyouforgotten_get

        GET haveyouforgotten  # noqa: E501
        """
        pass

    def test_apis_ui_search_products_post(self):
        """Test case for apis_ui_search_products_post

        POST products  # noqa: E501
        """
        pass

    def test_apis_ui_search_suggestion_get(self):
        """Test case for apis_ui_search_suggestion_get

        GET suggestion  # noqa: E501
        """
        pass

    def test_apis_ui_seo_metatags_post(self):
        """Test case for apis_ui_seo_metatags_post

        POST seometatags  # noqa: E501
        """
        pass

    def test_apis_ui_settings_get(self):
        """Test case for apis_ui_settings_get

        GET settings  # noqa: E501
        """
        pass

    def test_apis_ui_shopper_authentication_method_get(self):
        """Test case for apis_ui_shopper_authentication_method_get

        GET authenticationmethod  # noqa: E501
        """
        pass

    def test_apis_ui_trolley_get(self):
        """Test case for apis_ui_trolley_get

        GET trolley  # noqa: E501
        """
        pass

    def test_apis_ui_trolley_remove_post(self):
        """Test case for apis_ui_trolley_remove_post

        POST remove  # noqa: E501
        """
        pass

    def test_apis_ui_trolley_update_or_remove_items_post(self):
        """Test case for apis_ui_trolley_update_or_remove_items_post

        POST updateorremoveitems  # noqa: E501
        """
        pass

    def test_apis_ui_user_preferences_has_done_checkout_onboarding_post(self):
        """Test case for apis_ui_user_preferences_has_done_checkout_onboarding_post

        POST hasdonecheckoutonboarding  # noqa: E501
        """
        pass

    def test_apis_ui_v2_search_count_get(self):
        """Test case for apis_ui_v2_search_count_get

        GET count  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
