# coding: utf-8

"""
    flows_filtered Mitmproxy2Swagger

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import woolworths
from woolworths.models.trolley_remove_body import TrolleyRemoveBody  # noqa: E501
from woolworths.rest import ApiException


class TestTrolleyRemoveBody(unittest.TestCase):
    """TrolleyRemoveBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrolleyRemoveBody(self):
        """Test TrolleyRemoveBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = woolworths.models.trolley_remove_body.TrolleyRemoveBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
