# coding: utf-8

"""
    flows_filtered Mitmproxy2Swagger

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import woolworths
from woolworths.models.user_preferences_has_done_checkout_onboarding_body import UserPreferencesHasDoneCheckoutOnboardingBody  # noqa: E501
from woolworths.rest import ApiException


class TestUserPreferencesHasDoneCheckoutOnboardingBody(unittest.TestCase):
    """UserPreferencesHasDoneCheckoutOnboardingBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserPreferencesHasDoneCheckoutOnboardingBody(self):
        """Test UserPreferencesHasDoneCheckoutOnboardingBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = woolworths.models.user_preferences_has_done_checkout_onboarding_body.UserPreferencesHasDoneCheckoutOnboardingBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
