# coding: utf-8

"""
    flows_filtered Mitmproxy2Swagger

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import woolworths
from woolworths.models.trolley_update_body import TrolleyUpdateBody  # noqa: E501
from woolworths.rest import ApiException


class TestTrolleyUpdateBody(unittest.TestCase):
    """TrolleyUpdateBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrolleyUpdateBody(self):
        """Test TrolleyUpdateBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = woolworths.models.trolley_update_body.TrolleyUpdateBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
