# coding: utf-8

"""
    flows_filtered Mitmproxy2Swagger

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import woolworths
from woolworths.models.login_loginwithcredential_body import LoginLoginwithcredentialBody  # noqa: E501
from woolworths.rest import ApiException


class TestLoginLoginwithcredentialBody(unittest.TestCase):
    """LoginLoginwithcredentialBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoginLoginwithcredentialBody(self):
        """Test LoginLoginwithcredentialBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = woolworths.models.login_loginwithcredential_body.LoginLoginwithcredentialBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
