# coding: utf-8

"""
    flows_filtered Mitmproxy2Swagger

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AuthenticationOtpBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'one_time_pin': 'str',
        'update_primary_contact': 'object'
    }

    attribute_map = {
        'one_time_pin': 'OneTimePin',
        'update_primary_contact': 'UpdatePrimaryContact'
    }

    def __init__(self, one_time_pin=None, update_primary_contact=None):  # noqa: E501
        """AuthenticationOtpBody - a model defined in Swagger"""  # noqa: E501
        self._one_time_pin = None
        self._update_primary_contact = None
        self.discriminator = None
        if one_time_pin is not None:
            self.one_time_pin = one_time_pin
        if update_primary_contact is not None:
            self.update_primary_contact = update_primary_contact

    @property
    def one_time_pin(self):
        """Gets the one_time_pin of this AuthenticationOtpBody.  # noqa: E501


        :return: The one_time_pin of this AuthenticationOtpBody.  # noqa: E501
        :rtype: str
        """
        return self._one_time_pin

    @one_time_pin.setter
    def one_time_pin(self, one_time_pin):
        """Sets the one_time_pin of this AuthenticationOtpBody.


        :param one_time_pin: The one_time_pin of this AuthenticationOtpBody.  # noqa: E501
        :type: str
        """

        self._one_time_pin = one_time_pin

    @property
    def update_primary_contact(self):
        """Gets the update_primary_contact of this AuthenticationOtpBody.  # noqa: E501


        :return: The update_primary_contact of this AuthenticationOtpBody.  # noqa: E501
        :rtype: object
        """
        return self._update_primary_contact

    @update_primary_contact.setter
    def update_primary_contact(self, update_primary_contact):
        """Sets the update_primary_contact of this AuthenticationOtpBody.


        :param update_primary_contact: The update_primary_contact of this AuthenticationOtpBody.  # noqa: E501
        :type: object
        """

        self._update_primary_contact = update_primary_contact

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuthenticationOtpBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuthenticationOtpBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
