# coding: utf-8

"""
    flows_filtered Mitmproxy2Swagger

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DeliveryOptionsBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'can_leave_unattended': 'bool',
        'delivery_instructions': 'str'
    }

    attribute_map = {
        'can_leave_unattended': 'CanLeaveUnattended',
        'delivery_instructions': 'DeliveryInstructions'
    }

    def __init__(self, can_leave_unattended=None, delivery_instructions=None):  # noqa: E501
        """DeliveryOptionsBody - a model defined in Swagger"""  # noqa: E501
        self._can_leave_unattended = None
        self._delivery_instructions = None
        self.discriminator = None
        if can_leave_unattended is not None:
            self.can_leave_unattended = can_leave_unattended
        if delivery_instructions is not None:
            self.delivery_instructions = delivery_instructions

    @property
    def can_leave_unattended(self):
        """Gets the can_leave_unattended of this DeliveryOptionsBody.  # noqa: E501


        :return: The can_leave_unattended of this DeliveryOptionsBody.  # noqa: E501
        :rtype: bool
        """
        return self._can_leave_unattended

    @can_leave_unattended.setter
    def can_leave_unattended(self, can_leave_unattended):
        """Sets the can_leave_unattended of this DeliveryOptionsBody.


        :param can_leave_unattended: The can_leave_unattended of this DeliveryOptionsBody.  # noqa: E501
        :type: bool
        """

        self._can_leave_unattended = can_leave_unattended

    @property
    def delivery_instructions(self):
        """Gets the delivery_instructions of this DeliveryOptionsBody.  # noqa: E501


        :return: The delivery_instructions of this DeliveryOptionsBody.  # noqa: E501
        :rtype: str
        """
        return self._delivery_instructions

    @delivery_instructions.setter
    def delivery_instructions(self, delivery_instructions):
        """Sets the delivery_instructions of this DeliveryOptionsBody.


        :param delivery_instructions: The delivery_instructions of this DeliveryOptionsBody.  # noqa: E501
        :type: str
        """

        self._delivery_instructions = delivery_instructions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DeliveryOptionsBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeliveryOptionsBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
