# coding: utf-8

"""
    flows_filtered Mitmproxy2Swagger

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20022(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_successful': 'bool',
        'message': 'object',
        'is_non_serviced': 'bool',
        'market_message': 'object'
    }

    attribute_map = {
        'is_successful': 'IsSuccessful',
        'message': 'Message',
        'is_non_serviced': 'IsNonServiced',
        'market_message': 'MarketMessage'
    }

    def __init__(self, is_successful=None, message=None, is_non_serviced=None, market_message=None):  # noqa: E501
        """InlineResponse20022 - a model defined in Swagger"""  # noqa: E501
        self._is_successful = None
        self._message = None
        self._is_non_serviced = None
        self._market_message = None
        self.discriminator = None
        if is_successful is not None:
            self.is_successful = is_successful
        if message is not None:
            self.message = message
        if is_non_serviced is not None:
            self.is_non_serviced = is_non_serviced
        if market_message is not None:
            self.market_message = market_message

    @property
    def is_successful(self):
        """Gets the is_successful of this InlineResponse20022.  # noqa: E501


        :return: The is_successful of this InlineResponse20022.  # noqa: E501
        :rtype: bool
        """
        return self._is_successful

    @is_successful.setter
    def is_successful(self, is_successful):
        """Sets the is_successful of this InlineResponse20022.


        :param is_successful: The is_successful of this InlineResponse20022.  # noqa: E501
        :type: bool
        """

        self._is_successful = is_successful

    @property
    def message(self):
        """Gets the message of this InlineResponse20022.  # noqa: E501


        :return: The message of this InlineResponse20022.  # noqa: E501
        :rtype: object
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this InlineResponse20022.


        :param message: The message of this InlineResponse20022.  # noqa: E501
        :type: object
        """

        self._message = message

    @property
    def is_non_serviced(self):
        """Gets the is_non_serviced of this InlineResponse20022.  # noqa: E501


        :return: The is_non_serviced of this InlineResponse20022.  # noqa: E501
        :rtype: bool
        """
        return self._is_non_serviced

    @is_non_serviced.setter
    def is_non_serviced(self, is_non_serviced):
        """Sets the is_non_serviced of this InlineResponse20022.


        :param is_non_serviced: The is_non_serviced of this InlineResponse20022.  # noqa: E501
        :type: bool
        """

        self._is_non_serviced = is_non_serviced

    @property
    def market_message(self):
        """Gets the market_message of this InlineResponse20022.  # noqa: E501


        :return: The market_message of this InlineResponse20022.  # noqa: E501
        :rtype: object
        """
        return self._market_message

    @market_message.setter
    def market_message(self, market_message):
        """Sets the market_message of this InlineResponse20022.


        :param market_message: The market_message of this InlineResponse20022.  # noqa: E501
        :type: object
        """

        self._market_message = market_message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20022, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20022):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
