# coding: utf-8

"""
    flows_filtered Mitmproxy2Swagger

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20029(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'order': 'object',
        'can_leave_order_unattended': 'bool',
        'contains_age_restricted': 'bool',
        'contains_market_age_restricted': 'bool',
        'contains_frozen': 'bool',
        'contains_restricted_by_signature': 'bool',
        'contains_restricted_by_signature_and_photo_id': 'bool',
        'is_pushed_to_gtm': 'bool',
        'is_pushed_to_dtm': 'bool',
        'store': 'object'
    }

    attribute_map = {
        'order': 'Order',
        'can_leave_order_unattended': 'CanLeaveOrderUnattended',
        'contains_age_restricted': 'ContainsAgeRestricted',
        'contains_market_age_restricted': 'ContainsMarketAgeRestricted',
        'contains_frozen': 'ContainsFrozen',
        'contains_restricted_by_signature': 'ContainsRestrictedBySignature',
        'contains_restricted_by_signature_and_photo_id': 'ContainsRestrictedBySignatureAndPhotoId',
        'is_pushed_to_gtm': 'IsPushedToGtm',
        'is_pushed_to_dtm': 'IsPushedToDtm',
        'store': 'Store'
    }

    def __init__(self, order=None, can_leave_order_unattended=None, contains_age_restricted=None, contains_market_age_restricted=None, contains_frozen=None, contains_restricted_by_signature=None, contains_restricted_by_signature_and_photo_id=None, is_pushed_to_gtm=None, is_pushed_to_dtm=None, store=None):  # noqa: E501
        """InlineResponse20029 - a model defined in Swagger"""  # noqa: E501
        self._order = None
        self._can_leave_order_unattended = None
        self._contains_age_restricted = None
        self._contains_market_age_restricted = None
        self._contains_frozen = None
        self._contains_restricted_by_signature = None
        self._contains_restricted_by_signature_and_photo_id = None
        self._is_pushed_to_gtm = None
        self._is_pushed_to_dtm = None
        self._store = None
        self.discriminator = None
        if order is not None:
            self.order = order
        if can_leave_order_unattended is not None:
            self.can_leave_order_unattended = can_leave_order_unattended
        if contains_age_restricted is not None:
            self.contains_age_restricted = contains_age_restricted
        if contains_market_age_restricted is not None:
            self.contains_market_age_restricted = contains_market_age_restricted
        if contains_frozen is not None:
            self.contains_frozen = contains_frozen
        if contains_restricted_by_signature is not None:
            self.contains_restricted_by_signature = contains_restricted_by_signature
        if contains_restricted_by_signature_and_photo_id is not None:
            self.contains_restricted_by_signature_and_photo_id = contains_restricted_by_signature_and_photo_id
        if is_pushed_to_gtm is not None:
            self.is_pushed_to_gtm = is_pushed_to_gtm
        if is_pushed_to_dtm is not None:
            self.is_pushed_to_dtm = is_pushed_to_dtm
        if store is not None:
            self.store = store

    @property
    def order(self):
        """Gets the order of this InlineResponse20029.  # noqa: E501


        :return: The order of this InlineResponse20029.  # noqa: E501
        :rtype: object
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this InlineResponse20029.


        :param order: The order of this InlineResponse20029.  # noqa: E501
        :type: object
        """

        self._order = order

    @property
    def can_leave_order_unattended(self):
        """Gets the can_leave_order_unattended of this InlineResponse20029.  # noqa: E501


        :return: The can_leave_order_unattended of this InlineResponse20029.  # noqa: E501
        :rtype: bool
        """
        return self._can_leave_order_unattended

    @can_leave_order_unattended.setter
    def can_leave_order_unattended(self, can_leave_order_unattended):
        """Sets the can_leave_order_unattended of this InlineResponse20029.


        :param can_leave_order_unattended: The can_leave_order_unattended of this InlineResponse20029.  # noqa: E501
        :type: bool
        """

        self._can_leave_order_unattended = can_leave_order_unattended

    @property
    def contains_age_restricted(self):
        """Gets the contains_age_restricted of this InlineResponse20029.  # noqa: E501


        :return: The contains_age_restricted of this InlineResponse20029.  # noqa: E501
        :rtype: bool
        """
        return self._contains_age_restricted

    @contains_age_restricted.setter
    def contains_age_restricted(self, contains_age_restricted):
        """Sets the contains_age_restricted of this InlineResponse20029.


        :param contains_age_restricted: The contains_age_restricted of this InlineResponse20029.  # noqa: E501
        :type: bool
        """

        self._contains_age_restricted = contains_age_restricted

    @property
    def contains_market_age_restricted(self):
        """Gets the contains_market_age_restricted of this InlineResponse20029.  # noqa: E501


        :return: The contains_market_age_restricted of this InlineResponse20029.  # noqa: E501
        :rtype: bool
        """
        return self._contains_market_age_restricted

    @contains_market_age_restricted.setter
    def contains_market_age_restricted(self, contains_market_age_restricted):
        """Sets the contains_market_age_restricted of this InlineResponse20029.


        :param contains_market_age_restricted: The contains_market_age_restricted of this InlineResponse20029.  # noqa: E501
        :type: bool
        """

        self._contains_market_age_restricted = contains_market_age_restricted

    @property
    def contains_frozen(self):
        """Gets the contains_frozen of this InlineResponse20029.  # noqa: E501


        :return: The contains_frozen of this InlineResponse20029.  # noqa: E501
        :rtype: bool
        """
        return self._contains_frozen

    @contains_frozen.setter
    def contains_frozen(self, contains_frozen):
        """Sets the contains_frozen of this InlineResponse20029.


        :param contains_frozen: The contains_frozen of this InlineResponse20029.  # noqa: E501
        :type: bool
        """

        self._contains_frozen = contains_frozen

    @property
    def contains_restricted_by_signature(self):
        """Gets the contains_restricted_by_signature of this InlineResponse20029.  # noqa: E501


        :return: The contains_restricted_by_signature of this InlineResponse20029.  # noqa: E501
        :rtype: bool
        """
        return self._contains_restricted_by_signature

    @contains_restricted_by_signature.setter
    def contains_restricted_by_signature(self, contains_restricted_by_signature):
        """Sets the contains_restricted_by_signature of this InlineResponse20029.


        :param contains_restricted_by_signature: The contains_restricted_by_signature of this InlineResponse20029.  # noqa: E501
        :type: bool
        """

        self._contains_restricted_by_signature = contains_restricted_by_signature

    @property
    def contains_restricted_by_signature_and_photo_id(self):
        """Gets the contains_restricted_by_signature_and_photo_id of this InlineResponse20029.  # noqa: E501


        :return: The contains_restricted_by_signature_and_photo_id of this InlineResponse20029.  # noqa: E501
        :rtype: bool
        """
        return self._contains_restricted_by_signature_and_photo_id

    @contains_restricted_by_signature_and_photo_id.setter
    def contains_restricted_by_signature_and_photo_id(self, contains_restricted_by_signature_and_photo_id):
        """Sets the contains_restricted_by_signature_and_photo_id of this InlineResponse20029.


        :param contains_restricted_by_signature_and_photo_id: The contains_restricted_by_signature_and_photo_id of this InlineResponse20029.  # noqa: E501
        :type: bool
        """

        self._contains_restricted_by_signature_and_photo_id = contains_restricted_by_signature_and_photo_id

    @property
    def is_pushed_to_gtm(self):
        """Gets the is_pushed_to_gtm of this InlineResponse20029.  # noqa: E501


        :return: The is_pushed_to_gtm of this InlineResponse20029.  # noqa: E501
        :rtype: bool
        """
        return self._is_pushed_to_gtm

    @is_pushed_to_gtm.setter
    def is_pushed_to_gtm(self, is_pushed_to_gtm):
        """Sets the is_pushed_to_gtm of this InlineResponse20029.


        :param is_pushed_to_gtm: The is_pushed_to_gtm of this InlineResponse20029.  # noqa: E501
        :type: bool
        """

        self._is_pushed_to_gtm = is_pushed_to_gtm

    @property
    def is_pushed_to_dtm(self):
        """Gets the is_pushed_to_dtm of this InlineResponse20029.  # noqa: E501


        :return: The is_pushed_to_dtm of this InlineResponse20029.  # noqa: E501
        :rtype: bool
        """
        return self._is_pushed_to_dtm

    @is_pushed_to_dtm.setter
    def is_pushed_to_dtm(self, is_pushed_to_dtm):
        """Sets the is_pushed_to_dtm of this InlineResponse20029.


        :param is_pushed_to_dtm: The is_pushed_to_dtm of this InlineResponse20029.  # noqa: E501
        :type: bool
        """

        self._is_pushed_to_dtm = is_pushed_to_dtm

    @property
    def store(self):
        """Gets the store of this InlineResponse20029.  # noqa: E501


        :return: The store of this InlineResponse20029.  # noqa: E501
        :rtype: object
        """
        return self._store

    @store.setter
    def store(self, store):
        """Sets the store of this InlineResponse20029.


        :param store: The store of this InlineResponse20029.  # noqa: E501
        :type: object
        """

        self._store = store

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20029, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20029):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
