# coding: utf-8

"""
    flows_filtered Mitmproxy2Swagger

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2006(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'successful': 'bool',
        'error': 'object',
        'token_value': 'str',
        'error_message': 'object'
    }

    attribute_map = {
        'successful': 'Successful',
        'error': 'Error',
        'token_value': 'TokenValue',
        'error_message': 'ErrorMessage'
    }

    def __init__(self, successful=None, error=None, token_value=None, error_message=None):  # noqa: E501
        """InlineResponse2006 - a model defined in Swagger"""  # noqa: E501
        self._successful = None
        self._error = None
        self._token_value = None
        self._error_message = None
        self.discriminator = None
        if successful is not None:
            self.successful = successful
        if error is not None:
            self.error = error
        if token_value is not None:
            self.token_value = token_value
        if error_message is not None:
            self.error_message = error_message

    @property
    def successful(self):
        """Gets the successful of this InlineResponse2006.  # noqa: E501


        :return: The successful of this InlineResponse2006.  # noqa: E501
        :rtype: bool
        """
        return self._successful

    @successful.setter
    def successful(self, successful):
        """Sets the successful of this InlineResponse2006.


        :param successful: The successful of this InlineResponse2006.  # noqa: E501
        :type: bool
        """

        self._successful = successful

    @property
    def error(self):
        """Gets the error of this InlineResponse2006.  # noqa: E501


        :return: The error of this InlineResponse2006.  # noqa: E501
        :rtype: object
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this InlineResponse2006.


        :param error: The error of this InlineResponse2006.  # noqa: E501
        :type: object
        """

        self._error = error

    @property
    def token_value(self):
        """Gets the token_value of this InlineResponse2006.  # noqa: E501


        :return: The token_value of this InlineResponse2006.  # noqa: E501
        :rtype: str
        """
        return self._token_value

    @token_value.setter
    def token_value(self, token_value):
        """Sets the token_value of this InlineResponse2006.


        :param token_value: The token_value of this InlineResponse2006.  # noqa: E501
        :type: str
        """

        self._token_value = token_value

    @property
    def error_message(self):
        """Gets the error_message of this InlineResponse2006.  # noqa: E501


        :return: The error_message of this InlineResponse2006.  # noqa: E501
        :rtype: object
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this InlineResponse2006.


        :param error_message: The error_message of this InlineResponse2006.  # noqa: E501
        :type: object
        """

        self._error_message = error_message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2006, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2006):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
