# coding: utf-8

"""
    flows_filtered Mitmproxy2Swagger

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20024(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fee_structure_id': 'float',
        'fee_group': 'list[object]'
    }

    attribute_map = {
        'fee_structure_id': 'FeeStructureId',
        'fee_group': 'FeeGroup'
    }

    def __init__(self, fee_structure_id=None, fee_group=None):  # noqa: E501
        """InlineResponse20024 - a model defined in Swagger"""  # noqa: E501
        self._fee_structure_id = None
        self._fee_group = None
        self.discriminator = None
        if fee_structure_id is not None:
            self.fee_structure_id = fee_structure_id
        if fee_group is not None:
            self.fee_group = fee_group

    @property
    def fee_structure_id(self):
        """Gets the fee_structure_id of this InlineResponse20024.  # noqa: E501


        :return: The fee_structure_id of this InlineResponse20024.  # noqa: E501
        :rtype: float
        """
        return self._fee_structure_id

    @fee_structure_id.setter
    def fee_structure_id(self, fee_structure_id):
        """Sets the fee_structure_id of this InlineResponse20024.


        :param fee_structure_id: The fee_structure_id of this InlineResponse20024.  # noqa: E501
        :type: float
        """

        self._fee_structure_id = fee_structure_id

    @property
    def fee_group(self):
        """Gets the fee_group of this InlineResponse20024.  # noqa: E501


        :return: The fee_group of this InlineResponse20024.  # noqa: E501
        :rtype: list[object]
        """
        return self._fee_group

    @fee_group.setter
    def fee_group(self, fee_group):
        """Sets the fee_group of this InlineResponse20024.


        :param fee_group: The fee_group of this InlineResponse20024.  # noqa: E501
        :type: list[object]
        """

        self._fee_group = fee_group

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20024, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20024):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
