# coding: utf-8

"""
    flows_filtered Mitmproxy2Swagger

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2008(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'totals': 'object',
        'available_items': 'list[object]',
        'unavailable_items': 'list[object]',
        'exceeded_atp_limit_items': 'list[object]',
        'unavailable_by_market_out_of_stock_items': 'list[object]',
        'restricted_items': 'list[object]',
        'bundle_items': 'list[object]',
        'restricted_by_delivery_method_items': 'list[object]',
        'restricted_by_deli_platters_items': 'list[object]',
        'exceeded_supply_limit_items': 'list[object]',
        'delivery_fee': 'object',
        'market_shipping_fees': 'object',
        'market_delivery_details': 'object',
        'potential_order_promotions': 'list[object]',
        'message': 'object',
        'restricted_by_delivery_method_message': 'object',
        'restricted_by_deli_platters_message': 'object',
        'restricted_by_delivery_window_message': 'object',
        'product_group_supply_limit_window_warning_message': 'object',
        'trolley_item_count': 'float',
        'total_trolley_item_quantity': 'float',
        'total_wow_delivery_trolley_item_quantity': 'float',
        'maximum_order_quantity': 'float',
        'wow_rewards_summary': 'object',
        'tax_rate': 'float',
        'boosted': 'bool'
    }

    attribute_map = {
        'totals': 'Totals',
        'available_items': 'AvailableItems',
        'unavailable_items': 'UnavailableItems',
        'exceeded_atp_limit_items': 'ExceededAtpLimitItems',
        'unavailable_by_market_out_of_stock_items': 'UnavailableByMarketOutOfStockItems',
        'restricted_items': 'RestrictedItems',
        'bundle_items': 'BundleItems',
        'restricted_by_delivery_method_items': 'RestrictedByDeliveryMethodItems',
        'restricted_by_deli_platters_items': 'RestrictedByDeliPlattersItems',
        'exceeded_supply_limit_items': 'ExceededSupplyLimitItems',
        'delivery_fee': 'DeliveryFee',
        'market_shipping_fees': 'MarketShippingFees',
        'market_delivery_details': 'MarketDeliveryDetails',
        'potential_order_promotions': 'PotentialOrderPromotions',
        'message': 'Message',
        'restricted_by_delivery_method_message': 'RestrictedByDeliveryMethodMessage',
        'restricted_by_deli_platters_message': 'RestrictedByDeliPlattersMessage',
        'restricted_by_delivery_window_message': 'RestrictedByDeliveryWindowMessage',
        'product_group_supply_limit_window_warning_message': 'ProductGroupSupplyLimitWindowWarningMessage',
        'trolley_item_count': 'TrolleyItemCount',
        'total_trolley_item_quantity': 'TotalTrolleyItemQuantity',
        'total_wow_delivery_trolley_item_quantity': 'TotalWowDeliveryTrolleyItemQuantity',
        'maximum_order_quantity': 'MaximumOrderQuantity',
        'wow_rewards_summary': 'WowRewardsSummary',
        'tax_rate': 'TaxRate',
        'boosted': 'Boosted'
    }

    def __init__(self, totals=None, available_items=None, unavailable_items=None, exceeded_atp_limit_items=None, unavailable_by_market_out_of_stock_items=None, restricted_items=None, bundle_items=None, restricted_by_delivery_method_items=None, restricted_by_deli_platters_items=None, exceeded_supply_limit_items=None, delivery_fee=None, market_shipping_fees=None, market_delivery_details=None, potential_order_promotions=None, message=None, restricted_by_delivery_method_message=None, restricted_by_deli_platters_message=None, restricted_by_delivery_window_message=None, product_group_supply_limit_window_warning_message=None, trolley_item_count=None, total_trolley_item_quantity=None, total_wow_delivery_trolley_item_quantity=None, maximum_order_quantity=None, wow_rewards_summary=None, tax_rate=None, boosted=None):  # noqa: E501
        """InlineResponse2008 - a model defined in Swagger"""  # noqa: E501
        self._totals = None
        self._available_items = None
        self._unavailable_items = None
        self._exceeded_atp_limit_items = None
        self._unavailable_by_market_out_of_stock_items = None
        self._restricted_items = None
        self._bundle_items = None
        self._restricted_by_delivery_method_items = None
        self._restricted_by_deli_platters_items = None
        self._exceeded_supply_limit_items = None
        self._delivery_fee = None
        self._market_shipping_fees = None
        self._market_delivery_details = None
        self._potential_order_promotions = None
        self._message = None
        self._restricted_by_delivery_method_message = None
        self._restricted_by_deli_platters_message = None
        self._restricted_by_delivery_window_message = None
        self._product_group_supply_limit_window_warning_message = None
        self._trolley_item_count = None
        self._total_trolley_item_quantity = None
        self._total_wow_delivery_trolley_item_quantity = None
        self._maximum_order_quantity = None
        self._wow_rewards_summary = None
        self._tax_rate = None
        self._boosted = None
        self.discriminator = None
        if totals is not None:
            self.totals = totals
        if available_items is not None:
            self.available_items = available_items
        if unavailable_items is not None:
            self.unavailable_items = unavailable_items
        if exceeded_atp_limit_items is not None:
            self.exceeded_atp_limit_items = exceeded_atp_limit_items
        if unavailable_by_market_out_of_stock_items is not None:
            self.unavailable_by_market_out_of_stock_items = unavailable_by_market_out_of_stock_items
        if restricted_items is not None:
            self.restricted_items = restricted_items
        if bundle_items is not None:
            self.bundle_items = bundle_items
        if restricted_by_delivery_method_items is not None:
            self.restricted_by_delivery_method_items = restricted_by_delivery_method_items
        if restricted_by_deli_platters_items is not None:
            self.restricted_by_deli_platters_items = restricted_by_deli_platters_items
        if exceeded_supply_limit_items is not None:
            self.exceeded_supply_limit_items = exceeded_supply_limit_items
        if delivery_fee is not None:
            self.delivery_fee = delivery_fee
        if market_shipping_fees is not None:
            self.market_shipping_fees = market_shipping_fees
        if market_delivery_details is not None:
            self.market_delivery_details = market_delivery_details
        if potential_order_promotions is not None:
            self.potential_order_promotions = potential_order_promotions
        if message is not None:
            self.message = message
        if restricted_by_delivery_method_message is not None:
            self.restricted_by_delivery_method_message = restricted_by_delivery_method_message
        if restricted_by_deli_platters_message is not None:
            self.restricted_by_deli_platters_message = restricted_by_deli_platters_message
        if restricted_by_delivery_window_message is not None:
            self.restricted_by_delivery_window_message = restricted_by_delivery_window_message
        if product_group_supply_limit_window_warning_message is not None:
            self.product_group_supply_limit_window_warning_message = product_group_supply_limit_window_warning_message
        if trolley_item_count is not None:
            self.trolley_item_count = trolley_item_count
        if total_trolley_item_quantity is not None:
            self.total_trolley_item_quantity = total_trolley_item_quantity
        if total_wow_delivery_trolley_item_quantity is not None:
            self.total_wow_delivery_trolley_item_quantity = total_wow_delivery_trolley_item_quantity
        if maximum_order_quantity is not None:
            self.maximum_order_quantity = maximum_order_quantity
        if wow_rewards_summary is not None:
            self.wow_rewards_summary = wow_rewards_summary
        if tax_rate is not None:
            self.tax_rate = tax_rate
        if boosted is not None:
            self.boosted = boosted

    @property
    def totals(self):
        """Gets the totals of this InlineResponse2008.  # noqa: E501


        :return: The totals of this InlineResponse2008.  # noqa: E501
        :rtype: object
        """
        return self._totals

    @totals.setter
    def totals(self, totals):
        """Sets the totals of this InlineResponse2008.


        :param totals: The totals of this InlineResponse2008.  # noqa: E501
        :type: object
        """

        self._totals = totals

    @property
    def available_items(self):
        """Gets the available_items of this InlineResponse2008.  # noqa: E501


        :return: The available_items of this InlineResponse2008.  # noqa: E501
        :rtype: list[object]
        """
        return self._available_items

    @available_items.setter
    def available_items(self, available_items):
        """Sets the available_items of this InlineResponse2008.


        :param available_items: The available_items of this InlineResponse2008.  # noqa: E501
        :type: list[object]
        """

        self._available_items = available_items

    @property
    def unavailable_items(self):
        """Gets the unavailable_items of this InlineResponse2008.  # noqa: E501


        :return: The unavailable_items of this InlineResponse2008.  # noqa: E501
        :rtype: list[object]
        """
        return self._unavailable_items

    @unavailable_items.setter
    def unavailable_items(self, unavailable_items):
        """Sets the unavailable_items of this InlineResponse2008.


        :param unavailable_items: The unavailable_items of this InlineResponse2008.  # noqa: E501
        :type: list[object]
        """

        self._unavailable_items = unavailable_items

    @property
    def exceeded_atp_limit_items(self):
        """Gets the exceeded_atp_limit_items of this InlineResponse2008.  # noqa: E501


        :return: The exceeded_atp_limit_items of this InlineResponse2008.  # noqa: E501
        :rtype: list[object]
        """
        return self._exceeded_atp_limit_items

    @exceeded_atp_limit_items.setter
    def exceeded_atp_limit_items(self, exceeded_atp_limit_items):
        """Sets the exceeded_atp_limit_items of this InlineResponse2008.


        :param exceeded_atp_limit_items: The exceeded_atp_limit_items of this InlineResponse2008.  # noqa: E501
        :type: list[object]
        """

        self._exceeded_atp_limit_items = exceeded_atp_limit_items

    @property
    def unavailable_by_market_out_of_stock_items(self):
        """Gets the unavailable_by_market_out_of_stock_items of this InlineResponse2008.  # noqa: E501


        :return: The unavailable_by_market_out_of_stock_items of this InlineResponse2008.  # noqa: E501
        :rtype: list[object]
        """
        return self._unavailable_by_market_out_of_stock_items

    @unavailable_by_market_out_of_stock_items.setter
    def unavailable_by_market_out_of_stock_items(self, unavailable_by_market_out_of_stock_items):
        """Sets the unavailable_by_market_out_of_stock_items of this InlineResponse2008.


        :param unavailable_by_market_out_of_stock_items: The unavailable_by_market_out_of_stock_items of this InlineResponse2008.  # noqa: E501
        :type: list[object]
        """

        self._unavailable_by_market_out_of_stock_items = unavailable_by_market_out_of_stock_items

    @property
    def restricted_items(self):
        """Gets the restricted_items of this InlineResponse2008.  # noqa: E501


        :return: The restricted_items of this InlineResponse2008.  # noqa: E501
        :rtype: list[object]
        """
        return self._restricted_items

    @restricted_items.setter
    def restricted_items(self, restricted_items):
        """Sets the restricted_items of this InlineResponse2008.


        :param restricted_items: The restricted_items of this InlineResponse2008.  # noqa: E501
        :type: list[object]
        """

        self._restricted_items = restricted_items

    @property
    def bundle_items(self):
        """Gets the bundle_items of this InlineResponse2008.  # noqa: E501


        :return: The bundle_items of this InlineResponse2008.  # noqa: E501
        :rtype: list[object]
        """
        return self._bundle_items

    @bundle_items.setter
    def bundle_items(self, bundle_items):
        """Sets the bundle_items of this InlineResponse2008.


        :param bundle_items: The bundle_items of this InlineResponse2008.  # noqa: E501
        :type: list[object]
        """

        self._bundle_items = bundle_items

    @property
    def restricted_by_delivery_method_items(self):
        """Gets the restricted_by_delivery_method_items of this InlineResponse2008.  # noqa: E501


        :return: The restricted_by_delivery_method_items of this InlineResponse2008.  # noqa: E501
        :rtype: list[object]
        """
        return self._restricted_by_delivery_method_items

    @restricted_by_delivery_method_items.setter
    def restricted_by_delivery_method_items(self, restricted_by_delivery_method_items):
        """Sets the restricted_by_delivery_method_items of this InlineResponse2008.


        :param restricted_by_delivery_method_items: The restricted_by_delivery_method_items of this InlineResponse2008.  # noqa: E501
        :type: list[object]
        """

        self._restricted_by_delivery_method_items = restricted_by_delivery_method_items

    @property
    def restricted_by_deli_platters_items(self):
        """Gets the restricted_by_deli_platters_items of this InlineResponse2008.  # noqa: E501


        :return: The restricted_by_deli_platters_items of this InlineResponse2008.  # noqa: E501
        :rtype: list[object]
        """
        return self._restricted_by_deli_platters_items

    @restricted_by_deli_platters_items.setter
    def restricted_by_deli_platters_items(self, restricted_by_deli_platters_items):
        """Sets the restricted_by_deli_platters_items of this InlineResponse2008.


        :param restricted_by_deli_platters_items: The restricted_by_deli_platters_items of this InlineResponse2008.  # noqa: E501
        :type: list[object]
        """

        self._restricted_by_deli_platters_items = restricted_by_deli_platters_items

    @property
    def exceeded_supply_limit_items(self):
        """Gets the exceeded_supply_limit_items of this InlineResponse2008.  # noqa: E501


        :return: The exceeded_supply_limit_items of this InlineResponse2008.  # noqa: E501
        :rtype: list[object]
        """
        return self._exceeded_supply_limit_items

    @exceeded_supply_limit_items.setter
    def exceeded_supply_limit_items(self, exceeded_supply_limit_items):
        """Sets the exceeded_supply_limit_items of this InlineResponse2008.


        :param exceeded_supply_limit_items: The exceeded_supply_limit_items of this InlineResponse2008.  # noqa: E501
        :type: list[object]
        """

        self._exceeded_supply_limit_items = exceeded_supply_limit_items

    @property
    def delivery_fee(self):
        """Gets the delivery_fee of this InlineResponse2008.  # noqa: E501


        :return: The delivery_fee of this InlineResponse2008.  # noqa: E501
        :rtype: object
        """
        return self._delivery_fee

    @delivery_fee.setter
    def delivery_fee(self, delivery_fee):
        """Sets the delivery_fee of this InlineResponse2008.


        :param delivery_fee: The delivery_fee of this InlineResponse2008.  # noqa: E501
        :type: object
        """

        self._delivery_fee = delivery_fee

    @property
    def market_shipping_fees(self):
        """Gets the market_shipping_fees of this InlineResponse2008.  # noqa: E501


        :return: The market_shipping_fees of this InlineResponse2008.  # noqa: E501
        :rtype: object
        """
        return self._market_shipping_fees

    @market_shipping_fees.setter
    def market_shipping_fees(self, market_shipping_fees):
        """Sets the market_shipping_fees of this InlineResponse2008.


        :param market_shipping_fees: The market_shipping_fees of this InlineResponse2008.  # noqa: E501
        :type: object
        """

        self._market_shipping_fees = market_shipping_fees

    @property
    def market_delivery_details(self):
        """Gets the market_delivery_details of this InlineResponse2008.  # noqa: E501


        :return: The market_delivery_details of this InlineResponse2008.  # noqa: E501
        :rtype: object
        """
        return self._market_delivery_details

    @market_delivery_details.setter
    def market_delivery_details(self, market_delivery_details):
        """Sets the market_delivery_details of this InlineResponse2008.


        :param market_delivery_details: The market_delivery_details of this InlineResponse2008.  # noqa: E501
        :type: object
        """

        self._market_delivery_details = market_delivery_details

    @property
    def potential_order_promotions(self):
        """Gets the potential_order_promotions of this InlineResponse2008.  # noqa: E501


        :return: The potential_order_promotions of this InlineResponse2008.  # noqa: E501
        :rtype: list[object]
        """
        return self._potential_order_promotions

    @potential_order_promotions.setter
    def potential_order_promotions(self, potential_order_promotions):
        """Sets the potential_order_promotions of this InlineResponse2008.


        :param potential_order_promotions: The potential_order_promotions of this InlineResponse2008.  # noqa: E501
        :type: list[object]
        """

        self._potential_order_promotions = potential_order_promotions

    @property
    def message(self):
        """Gets the message of this InlineResponse2008.  # noqa: E501


        :return: The message of this InlineResponse2008.  # noqa: E501
        :rtype: object
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this InlineResponse2008.


        :param message: The message of this InlineResponse2008.  # noqa: E501
        :type: object
        """

        self._message = message

    @property
    def restricted_by_delivery_method_message(self):
        """Gets the restricted_by_delivery_method_message of this InlineResponse2008.  # noqa: E501


        :return: The restricted_by_delivery_method_message of this InlineResponse2008.  # noqa: E501
        :rtype: object
        """
        return self._restricted_by_delivery_method_message

    @restricted_by_delivery_method_message.setter
    def restricted_by_delivery_method_message(self, restricted_by_delivery_method_message):
        """Sets the restricted_by_delivery_method_message of this InlineResponse2008.


        :param restricted_by_delivery_method_message: The restricted_by_delivery_method_message of this InlineResponse2008.  # noqa: E501
        :type: object
        """

        self._restricted_by_delivery_method_message = restricted_by_delivery_method_message

    @property
    def restricted_by_deli_platters_message(self):
        """Gets the restricted_by_deli_platters_message of this InlineResponse2008.  # noqa: E501


        :return: The restricted_by_deli_platters_message of this InlineResponse2008.  # noqa: E501
        :rtype: object
        """
        return self._restricted_by_deli_platters_message

    @restricted_by_deli_platters_message.setter
    def restricted_by_deli_platters_message(self, restricted_by_deli_platters_message):
        """Sets the restricted_by_deli_platters_message of this InlineResponse2008.


        :param restricted_by_deli_platters_message: The restricted_by_deli_platters_message of this InlineResponse2008.  # noqa: E501
        :type: object
        """

        self._restricted_by_deli_platters_message = restricted_by_deli_platters_message

    @property
    def restricted_by_delivery_window_message(self):
        """Gets the restricted_by_delivery_window_message of this InlineResponse2008.  # noqa: E501


        :return: The restricted_by_delivery_window_message of this InlineResponse2008.  # noqa: E501
        :rtype: object
        """
        return self._restricted_by_delivery_window_message

    @restricted_by_delivery_window_message.setter
    def restricted_by_delivery_window_message(self, restricted_by_delivery_window_message):
        """Sets the restricted_by_delivery_window_message of this InlineResponse2008.


        :param restricted_by_delivery_window_message: The restricted_by_delivery_window_message of this InlineResponse2008.  # noqa: E501
        :type: object
        """

        self._restricted_by_delivery_window_message = restricted_by_delivery_window_message

    @property
    def product_group_supply_limit_window_warning_message(self):
        """Gets the product_group_supply_limit_window_warning_message of this InlineResponse2008.  # noqa: E501


        :return: The product_group_supply_limit_window_warning_message of this InlineResponse2008.  # noqa: E501
        :rtype: object
        """
        return self._product_group_supply_limit_window_warning_message

    @product_group_supply_limit_window_warning_message.setter
    def product_group_supply_limit_window_warning_message(self, product_group_supply_limit_window_warning_message):
        """Sets the product_group_supply_limit_window_warning_message of this InlineResponse2008.


        :param product_group_supply_limit_window_warning_message: The product_group_supply_limit_window_warning_message of this InlineResponse2008.  # noqa: E501
        :type: object
        """

        self._product_group_supply_limit_window_warning_message = product_group_supply_limit_window_warning_message

    @property
    def trolley_item_count(self):
        """Gets the trolley_item_count of this InlineResponse2008.  # noqa: E501


        :return: The trolley_item_count of this InlineResponse2008.  # noqa: E501
        :rtype: float
        """
        return self._trolley_item_count

    @trolley_item_count.setter
    def trolley_item_count(self, trolley_item_count):
        """Sets the trolley_item_count of this InlineResponse2008.


        :param trolley_item_count: The trolley_item_count of this InlineResponse2008.  # noqa: E501
        :type: float
        """

        self._trolley_item_count = trolley_item_count

    @property
    def total_trolley_item_quantity(self):
        """Gets the total_trolley_item_quantity of this InlineResponse2008.  # noqa: E501


        :return: The total_trolley_item_quantity of this InlineResponse2008.  # noqa: E501
        :rtype: float
        """
        return self._total_trolley_item_quantity

    @total_trolley_item_quantity.setter
    def total_trolley_item_quantity(self, total_trolley_item_quantity):
        """Sets the total_trolley_item_quantity of this InlineResponse2008.


        :param total_trolley_item_quantity: The total_trolley_item_quantity of this InlineResponse2008.  # noqa: E501
        :type: float
        """

        self._total_trolley_item_quantity = total_trolley_item_quantity

    @property
    def total_wow_delivery_trolley_item_quantity(self):
        """Gets the total_wow_delivery_trolley_item_quantity of this InlineResponse2008.  # noqa: E501


        :return: The total_wow_delivery_trolley_item_quantity of this InlineResponse2008.  # noqa: E501
        :rtype: float
        """
        return self._total_wow_delivery_trolley_item_quantity

    @total_wow_delivery_trolley_item_quantity.setter
    def total_wow_delivery_trolley_item_quantity(self, total_wow_delivery_trolley_item_quantity):
        """Sets the total_wow_delivery_trolley_item_quantity of this InlineResponse2008.


        :param total_wow_delivery_trolley_item_quantity: The total_wow_delivery_trolley_item_quantity of this InlineResponse2008.  # noqa: E501
        :type: float
        """

        self._total_wow_delivery_trolley_item_quantity = total_wow_delivery_trolley_item_quantity

    @property
    def maximum_order_quantity(self):
        """Gets the maximum_order_quantity of this InlineResponse2008.  # noqa: E501


        :return: The maximum_order_quantity of this InlineResponse2008.  # noqa: E501
        :rtype: float
        """
        return self._maximum_order_quantity

    @maximum_order_quantity.setter
    def maximum_order_quantity(self, maximum_order_quantity):
        """Sets the maximum_order_quantity of this InlineResponse2008.


        :param maximum_order_quantity: The maximum_order_quantity of this InlineResponse2008.  # noqa: E501
        :type: float
        """

        self._maximum_order_quantity = maximum_order_quantity

    @property
    def wow_rewards_summary(self):
        """Gets the wow_rewards_summary of this InlineResponse2008.  # noqa: E501


        :return: The wow_rewards_summary of this InlineResponse2008.  # noqa: E501
        :rtype: object
        """
        return self._wow_rewards_summary

    @wow_rewards_summary.setter
    def wow_rewards_summary(self, wow_rewards_summary):
        """Sets the wow_rewards_summary of this InlineResponse2008.


        :param wow_rewards_summary: The wow_rewards_summary of this InlineResponse2008.  # noqa: E501
        :type: object
        """

        self._wow_rewards_summary = wow_rewards_summary

    @property
    def tax_rate(self):
        """Gets the tax_rate of this InlineResponse2008.  # noqa: E501


        :return: The tax_rate of this InlineResponse2008.  # noqa: E501
        :rtype: float
        """
        return self._tax_rate

    @tax_rate.setter
    def tax_rate(self, tax_rate):
        """Sets the tax_rate of this InlineResponse2008.


        :param tax_rate: The tax_rate of this InlineResponse2008.  # noqa: E501
        :type: float
        """

        self._tax_rate = tax_rate

    @property
    def boosted(self):
        """Gets the boosted of this InlineResponse2008.  # noqa: E501


        :return: The boosted of this InlineResponse2008.  # noqa: E501
        :rtype: bool
        """
        return self._boosted

    @boosted.setter
    def boosted(self, boosted):
        """Sets the boosted of this InlineResponse2008.


        :param boosted: The boosted of this InlineResponse2008.  # noqa: E501
        :type: bool
        """

        self._boosted = boosted

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2008, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2008):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
