# coding: utf-8

"""
    flows_filtered Mitmproxy2Swagger

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2003(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'title': 'str',
        'meta_description': 'str',
        'groups': 'list[object]'
    }

    attribute_map = {
        'title': 'Title',
        'meta_description': 'MetaDescription',
        'groups': 'Groups'
    }

    def __init__(self, title=None, meta_description=None, groups=None):  # noqa: E501
        """InlineResponse2003 - a model defined in Swagger"""  # noqa: E501
        self._title = None
        self._meta_description = None
        self._groups = None
        self.discriminator = None
        if title is not None:
            self.title = title
        if meta_description is not None:
            self.meta_description = meta_description
        if groups is not None:
            self.groups = groups

    @property
    def title(self):
        """Gets the title of this InlineResponse2003.  # noqa: E501


        :return: The title of this InlineResponse2003.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this InlineResponse2003.


        :param title: The title of this InlineResponse2003.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def meta_description(self):
        """Gets the meta_description of this InlineResponse2003.  # noqa: E501


        :return: The meta_description of this InlineResponse2003.  # noqa: E501
        :rtype: str
        """
        return self._meta_description

    @meta_description.setter
    def meta_description(self, meta_description):
        """Sets the meta_description of this InlineResponse2003.


        :param meta_description: The meta_description of this InlineResponse2003.  # noqa: E501
        :type: str
        """

        self._meta_description = meta_description

    @property
    def groups(self):
        """Gets the groups of this InlineResponse2003.  # noqa: E501


        :return: The groups of this InlineResponse2003.  # noqa: E501
        :rtype: list[object]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this InlineResponse2003.


        :param groups: The groups of this InlineResponse2003.  # noqa: E501
        :type: list[object]
        """

        self._groups = groups

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2003, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2003):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
