# coding: utf-8

"""
    flows_filtered Mitmproxy2Swagger

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20021(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'success': 'bool',
        'error_message': 'str',
        'iframe_url': 'str'
    }

    attribute_map = {
        'success': 'Success',
        'error_message': 'ErrorMessage',
        'iframe_url': 'IframeUrl'
    }

    def __init__(self, success=None, error_message=None, iframe_url=None):  # noqa: E501
        """InlineResponse20021 - a model defined in Swagger"""  # noqa: E501
        self._success = None
        self._error_message = None
        self._iframe_url = None
        self.discriminator = None
        if success is not None:
            self.success = success
        if error_message is not None:
            self.error_message = error_message
        if iframe_url is not None:
            self.iframe_url = iframe_url

    @property
    def success(self):
        """Gets the success of this InlineResponse20021.  # noqa: E501


        :return: The success of this InlineResponse20021.  # noqa: E501
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success):
        """Sets the success of this InlineResponse20021.


        :param success: The success of this InlineResponse20021.  # noqa: E501
        :type: bool
        """

        self._success = success

    @property
    def error_message(self):
        """Gets the error_message of this InlineResponse20021.  # noqa: E501


        :return: The error_message of this InlineResponse20021.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this InlineResponse20021.


        :param error_message: The error_message of this InlineResponse20021.  # noqa: E501
        :type: str
        """

        self._error_message = error_message

    @property
    def iframe_url(self):
        """Gets the iframe_url of this InlineResponse20021.  # noqa: E501


        :return: The iframe_url of this InlineResponse20021.  # noqa: E501
        :rtype: str
        """
        return self._iframe_url

    @iframe_url.setter
    def iframe_url(self, iframe_url):
        """Sets the iframe_url of this InlineResponse20021.


        :param iframe_url: The iframe_url of this InlineResponse20021.  # noqa: E501
        :type: str
        """

        self._iframe_url = iframe_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20021, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20021):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
