# coding: utf-8

"""
    flows_filtered Mitmproxy2Swagger

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TrolleyRemoveBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'stockcode': 'float',
        'evaluate_reward_points': 'bool'
    }

    attribute_map = {
        'stockcode': 'Stockcode',
        'evaluate_reward_points': 'evaluateRewardPoints'
    }

    def __init__(self, stockcode=None, evaluate_reward_points=None):  # noqa: E501
        """TrolleyRemoveBody - a model defined in Swagger"""  # noqa: E501
        self._stockcode = None
        self._evaluate_reward_points = None
        self.discriminator = None
        if stockcode is not None:
            self.stockcode = stockcode
        if evaluate_reward_points is not None:
            self.evaluate_reward_points = evaluate_reward_points

    @property
    def stockcode(self):
        """Gets the stockcode of this TrolleyRemoveBody.  # noqa: E501


        :return: The stockcode of this TrolleyRemoveBody.  # noqa: E501
        :rtype: float
        """
        return self._stockcode

    @stockcode.setter
    def stockcode(self, stockcode):
        """Sets the stockcode of this TrolleyRemoveBody.


        :param stockcode: The stockcode of this TrolleyRemoveBody.  # noqa: E501
        :type: float
        """

        self._stockcode = stockcode

    @property
    def evaluate_reward_points(self):
        """Gets the evaluate_reward_points of this TrolleyRemoveBody.  # noqa: E501


        :return: The evaluate_reward_points of this TrolleyRemoveBody.  # noqa: E501
        :rtype: bool
        """
        return self._evaluate_reward_points

    @evaluate_reward_points.setter
    def evaluate_reward_points(self, evaluate_reward_points):
        """Sets the evaluate_reward_points of this TrolleyRemoveBody.


        :param evaluate_reward_points: The evaluate_reward_points of this TrolleyRemoveBody.  # noqa: E501
        :type: bool
        """

        self._evaluate_reward_points = evaluate_reward_points

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TrolleyRemoveBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TrolleyRemoveBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
